# Generated by Django 4.2.6 on 2023-10-26 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='bookjournal',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='journal.book'),
        ),
    ]
