# Generated by Django 4.2.6 on 2023-10-26 03:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_book_alter_bookjournal_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('MGA', 'Manga'), ('LNV', 'Light-Novel'), ('DJS', 'Doujinshi'), ('MHW', 'Manhwa'), ('MHU', 'Manhua'), ('NVL', 'Novel'), ('OTH', 'Other')], default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='image_url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0, 'Score cannot be lower than 0'), django.core.validators.MaxValueValidator(10.0, 'Maximum score of a book is 10')]),
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='volumes',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Book has to have at least 1 volume')]),
        ),
    ]
