# Generated by Django 4.2.6 on 2023-10-27 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20231021_1519'),
        ('journal', '0003_book_book_type_book_image_url_book_score_book_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookjournal',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
