# Generated by Django 4.2.6 on 2023-10-27 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_bookjournal_book_delete_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookjournal',
            name='date_added',
        ),
        migrations.AddField(
            model_name='bookjournal',
            name='date_finished',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='bookjournal',
            name='date_started',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
