# Generated by Django 4.2.6 on 2023-10-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_remove_bookjournal_date_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookjournal',
            name='date_finished',
        ),
        migrations.RemoveField(
            model_name='bookjournal',
            name='date_started',
        ),
        migrations.AddField(
            model_name='bookjournal',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
