# Generated by Django 4.2.6 on 2023-10-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='donatur',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
