# Generated by Django 4.2.6 on 2023-10-28 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20231021_1519'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donate', '0002_book_donatur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdonate',
            name='user',
        ),
        migrations.AddField(
            model_name='bookdonate',
            name='donatur',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookdonate',
            name='kondisi',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookdonate',
            name='lembaga',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lembaga', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookdonate',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
