# Generated by Django 4.2.6 on 2023-10-28 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donate', '0003_remove_bookdonate_user_bookdonate_donatur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdonate',
            name='donatur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donatur', to=settings.AUTH_USER_MODEL),
        ),
    ]
