# Generated by Django 4.2.6 on 2023-10-29 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0005_bookdonate_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdonate',
            name='user',
        ),
    ]
