# Generated by Django 4.2.6 on 2023-10-18 09:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('book_type', models.CharField(choices=[('MGA', 'Manga'), ('LNV', 'Light-Novel'), ('DJS', 'Doujinshi'), ('MHW', 'Manhwa'), ('MHU', 'Manhua'), ('NVL', 'Novel'), ('OTH', 'Other')], max_length=3)),
                ('volumes', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Book has to have at least 1 volume')])),
                ('image_url', models.URLField()),
                ('score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0, 'Score cannot be lower than 0'), django.core.validators.MaxValueValidator(10.0, 'Maximum score of a book is 10')])),
            ],
        ),
        migrations.CreateModel(
            name='BoughtBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Amount cannot be lower than 1'), django.core.validators.MaxValueValidator(20, 'Maximum amount of books to buy is 20')])),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
