# Generated by Django 4.2.6 on 2023-12-20 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20231021_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
