# Generated by Django 4.2.5 on 2023-11-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="replie",
            name="post",
        ),
        migrations.RemoveField(
            model_name="replie",
            name="user",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="user",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="timestamp",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="post",
            name="post_content",
        ),
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.TextField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="", max_length=400),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
        migrations.DeleteModel(
            name="Replie",
        ),
    ]
