# Generated by Django 4.2.6 on 2023-12-11 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='takugouser',
            managers=[
            ],
        ),
    ]
